included:
  Sources

disabled_rules:
  - let_var_whitespace
  - number_separator
  - object_literal
  - prefixed_toplevel_constant
  - switch_case_on_newline
  - todo
  - type_name
  - unowned_variable_capture
  - unused_capture_list

opt_in_rules:
  - array_init
  - attributes
  - collection_alignment
  - closure_end_indentation
  - closure_spacing
  - conditional_returns_on_newline
  - contains_over_first_not_nil
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_range_nil_comparison
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - expiring_todo
  - extension_access_modifier
  - fatal_error_message
  - flatmap_over_map_reduce
  - file_header
  - file_name_no_space
  - first_where
  - function_default_parameter_at_end
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - multiple_closures_with_trailing_closure
  - nslocalizedstring_key
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prohibited_super_call
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition

file_header:
  required_pattern: (\/\/ Copyright \d{4} Itty Bitty Apps Pty Ltd\. See LICENSE file\.|\/\/ swift-tools-version:[\d\.]+)

identifier_name:
  excluded: [id, x, y, z, r, g, b, a, i, j, k, cx, cy, dx, dy]

line_length:
  ignores_comments: true
  ignores_function_declarations: true
  warning: 180

modifier_order:
  preferred_modifier_order:
    - acl
    - override

multiline_arguments:
  first_argument_location: next_line

nesting:
  type_level: 2

trailing_comma:
  mandatory_comma: true

