name: macOS Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: macos-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-macos-macos-12-matrix:
    runs-on: macos-12
    timeout-minutes: 10
    strategy:
      matrix:
        xcode: ["14.2"]

    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.0
      - name: Build
        run: swift build -c release
