name: Yaml Lint
on:
  pull_request:
    branches: [main]
    paths:
      - '**.yml'

concurrency:
  group: yamllint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: yaml-lint
        uses: reviewdog/action-yamllint@v1.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: error
          reporter: github-pr-review
          yamllint_flags: '.'
